#!/usr/bin/env python3
"""
Genera un archivo catalog.js con las fotos organizadas por categoría.
Lee la estructura de carpetas de downloads/clamacalma/ y genera un array JS.

Uso: python generate_catalog.py
"""

import os
import json

PHOTOS_DIR = os.path.join(os.path.dirname(__file__), "downloads", "clamacalma")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "catalog.js")

# Categorías que tienen modelo 3D (nombre carpeta → carpeta del modelo)
MODELS_3D = {
    "Tangram": "tangram3d",
    "Arco iris": "arcoiris3d",
    "Jenga": "jenga3d",
    "Cubo Soma": "cubosoma3d",
    "Ta-Te-Ti": "tateti3d",
}

# Orden preferido de categorías (las más vistosas primero)
CATEGORY_ORDER = [
    "Arco iris",
    "Tangram",
    "Encastre",
    "Mosaico",
    "Rompecabezas",
    "Jenga",
    "Cubo Soma",
    "Ola de equilibrio",
    "Arrastre",
    "Autos",
    "Tren",
    "Avion",
    "Frutas y verduras",
    "Ta-Te-Ti",
    "Piramide",
    "Animalitos para tejer",
    "Varios",
]

# Categorías a excluir
EXCLUDED = {"Biblioteca infantil", "Jenga"}

# Fotos individuales a excluir (personas visibles)
EXCLUDED_PHOTOS = {
    "2024-09-21_19-58-35__DAMRglvv8Gc_2.jpg",
    "2024-10-08_22-01-20__DA4REmXPKw3_2.jpg",
}


def main():
    categories = []

    for cat_name in CATEGORY_ORDER:
        if cat_name in EXCLUDED:
            continue
        cat_path = os.path.join(PHOTOS_DIR, cat_name)
        if not os.path.isdir(cat_path):
            continue

        photos = sorted([
            f for f in os.listdir(cat_path)
            if f.lower().endswith((".jpg", ".jpeg", ".png", ".webp"))
            and f not in EXCLUDED_PHOTOS
        ])

        if not photos:
            continue

        cat = {
            "name": cat_name,
            "slug": cat_name.lower().replace(" ", "-"),
            "photos": [f"downloads/clamacalma/{cat_name}/{p}" for p in photos],
            "thumbs": [f"downloads/clamacalma/{cat_name}/thumbs/{os.path.splitext(p)[0]}.jpg" for p in photos],
        }

        if cat_name in MODELS_3D:
            cat["model3d"] = MODELS_3D[cat_name]

        categories.append(cat)

    # Agregar categorías no listadas en CATEGORY_ORDER
    for entry in sorted(os.listdir(PHOTOS_DIR)):
        cat_path = os.path.join(PHOTOS_DIR, entry)
        if not os.path.isdir(cat_path) or entry in CATEGORY_ORDER or entry in EXCLUDED:
            continue
        photos = sorted([
            f for f in os.listdir(cat_path)
            if f.lower().endswith((".jpg", ".jpeg", ".png", ".webp"))
            and f not in EXCLUDED_PHOTOS
        ])
        if photos:
            categories.append({
                "name": entry,
                "slug": entry.lower().replace(" ", "-"),
                "photos": [f"downloads/clamacalma/{entry}/{p}" for p in photos],
                "thumbs": [f"downloads/clamacalma/{entry}/thumbs/{os.path.splitext(p)[0]}.jpg" for p in photos],
            })

    js = "// Auto-generated by generate_catalog.py — do not edit\n"
    js += f"const CATALOG = {json.dumps(categories, ensure_ascii=False, indent=2)};\n"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js)

    total = sum(len(c["photos"]) for c in categories)
    print(f"Generated {OUTPUT_FILE}: {len(categories)} categories, {total} photos")


if __name__ == "__main__":
    main()
